
POST http://localhost:3000/auth/change-password
Content-Type: application/json

{
    "userId": "67759c60-6b97-4c7c-9195-be7be551c821",
    "oldPassword": "lopta123",
    "newPassword": "newpassword123"
}
