### Add to Favorites
POST http://localhost:3000/favorites
Content-Type: application/json

{
    "userId": "67759c60-6b97-4c7c-9195-be7be551c821",
    "postId": "35e11cfc-a40c-495c-a5ce-6b805ca64c2c"
}

### Remove from Favorites
DELETE http://localhost:3000/favorites
Content-Type: application/json

{
    "userId": "67759c60-6b97-4c7c-9195-be7be551c821",
    "postId": "35e11cfc-a40c-495c-a5ce-6b805ca64c2c"
}

### Get User Favorites
GET http://localhost:3000/favorites/user/67759c60-6b97-4c7c-9195-be7be551c821

### Check if Post is Favorite
GET http://localhost:3000/favorites/check/user-id-here/35e11cfc-a40c-495c-a5ce-6b805ca64c2c
